services:
  host:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args: []
      labels: []
      network: host
    ports:
      - 80:80
      - 443:443
  database:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: administrat0r!
    image: mcr.microsoft.com/azure-sql-edge:1.0.4
    # If you really want to use MS SQL Server, uncomment the following line
    #image: mcr.microsoft.com/mssql/server
    ports:
      - 1434:1433
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1' || exit 1"
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  cache:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    restart: always
